name: 自动同步他人仓库
# 定时每天自动执行，也可以手动触发
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  同步任务:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 同步原作者仓库代码
        uses: aormsby/Fork-Sync-With-Upstream-action@v3
        with:
          # 不用改下面这行，自动识别仓库
          upstream_repository: ${{ github.repository_owner }}/${{ github.repository }}
          # 你要同步的分支，默认主分支 main
          target_branch: main
          upstream_branch: main
          git_user_name: 自动同步机器人
          git_user_email: sync@github.com
