name: awesome-gpt-image-2-API-and-Prompts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync with upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3
        with:
          upstream_repository: EvoLinkAI/awesome-gpt-image-2-API-and-Prompts
          target_branch: main
          upstream_branch: main
